[package]
name = "lion"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
cfg-if = "1.0.0"
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.20"
